# Generated by Django 4.2.7 on 2026-01-26 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olmachine_products', '0002_usercategoryview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFormConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable form for this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_config', to='olmachine_products.category')),
            ],
            options={
                'verbose_name': 'Category Form Configuration',
                'verbose_name_plural': 'Category Form Configurations',
                'db_table': 'category_form_configs',
            },
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('listed', 'Listed')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('form_data', models.JSONField(default=dict, help_text='Store all form field values as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to='olmachine_products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='olmachine_products.seller')),
            ],
            options={
                'verbose_name': 'Seller Product',
                'verbose_name_plural': 'Seller Products',
                'db_table': 'seller_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='olmachine_seller_portal.sellerproduct')),
            ],
            options={
                'verbose_name': 'Product Approval',
                'verbose_name_plural': 'Product Approvals',
                'db_table': 'product_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'brand', 'model')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Brand Name')", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('textarea', 'Textarea'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File'), ('date', 'Date'), ('email', 'Email'), ('url', 'URL')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text="Validation rules: {'min_length': 5, 'max_length': 100, 'regex': 'pattern'}")),
                ('options', models.JSONField(blank=True, default=list, help_text="For select/radio: [{'value': 'option1', 'label': 'Option 1'}]")),
                ('order', models.IntegerField(default=0, help_text='Display order of field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='olmachine_seller_portal.categoryformconfig')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'form_fields',
                'ordering': ['order', 'field_label'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='olmachine_products.seller')),
                ('user', models.ForeignKey(help_text='Link seller to authenticated user', on_delete=django.db.models.deletion.CASCADE, related_name='seller_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'db_table': 'seller_profiles',
                'indexes': [models.Index(fields=['user'], name='seller_prof_user_id_c6facc_idx'), models.Index(fields=['seller'], name='seller_prof_seller__e44ee9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['seller', 'status'], name='seller_prod_seller__07d9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['status'], name='seller_prod_status_7fa35c_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['created_at'], name='seller_prod_created_ae8827_idx'),
        ),
        migrations.AddIndex(
            model_name='productapproval',
            index=models.Index(fields=['seller_product', 'status'], name='product_app_seller__e4fa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form_config', 'order'], name='form_fields_form_co_706d3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form_config', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='categoryformconfig',
            index=models.Index(fields=['category', 'is_active'], name='category_fo_categor_e3caf7_idx'),
        ),
    ]
