# Generated by Django 4.2.7 on 2026-02-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olmachine_seller_portal', '0003_categoryformconfig_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categoryformconfig',
            new_name='category_fo_categor_e3caf7_idx',
            old_name='seller_formconfig_cat_act_idx',
        ),
    ]
