# Generated by Django 4.2.7 on 2026-01-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olmachine_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='olmachine_products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Category View',
                'verbose_name_plural': 'User Category Views',
                'db_table': 'user_category_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='user_catego_user_id_086b3a_idx'), models.Index(fields=['category'], name='user_catego_categor_25f881_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
