# Generated by Django 4.2.7 on 2026-01-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olmachine_products', '0002_usercategoryview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0, help_text='Depth level in hierarchy (0 = top level)'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for top-level categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='olmachine_products.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category', 'is_active', 'order'], name='categories_parent__c8f795_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'is_active'], name='categories_level_5da82b_idx'),
        ),
    ]
