# Generated by Django 4.2.7 on 2026-01-26 20:40

from django.db import migrations


def set_initial_category_levels(apps, schema_editor):
    """
    Set all existing categories to level 0 and parent_category=None.
    This ensures backward compatibility with existing data.
    """
    Category = apps.get_model('olmachine_products', 'Category')
    Category.objects.all().update(level=0, parent_category=None)


def reverse_set_initial_category_levels(apps, schema_editor):
    """
    Reverse migration - no action needed as we're just setting defaults.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('olmachine_products', '0003_alter_category_options_category_level_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_initial_category_levels,
            reverse_set_initial_category_levels
        ),
    ]
