# Generated by Django 4.2.7 on 2026-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olmachine_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username for admin users', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code for phone number', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for regular users', max_length=15, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='user_must_have_username_or_phone'),
        ),
    ]
